services:

  proxy:
    image: traefik:v3.5
    command:
      - --entrypoints.web.address=:80
      - --providers.docker=true
      - --api.insecure=true
      - --log.level=TRACE
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  octoprint:
    image: ciaranmcnulty/octoprint-docker:latest
    build:
      target: octoprint
      args:
        CONFIG_PRINTER: config/prusa_mk25s_profile.yaml
    restart: unless-stopped
    environment:
      LOGIN_USERNAME: ${OCTOPRINT_USERNAME}
    devices:
      - "${OCTOPRINT_PRINTER_TTY:-/dev/ttyACM0}"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.octoprint.rule=PathPrefix(`/`)"
      - "traefik.http.routers.octoprint.entrypoints=web"
      - "traefik.http.routers.octoprint.middlewares=auth"
      - "traefik.http.routers.octoprint.priority=1"
      - "traefik.http.middlewares.auth.basicauth.users=${HTTP_PASSWORD_HASH}"
      # Stop the web manifest and websocket requests from triggering http auth
      - "traefik.http.routers.assets.rule=PathPrefix(`/static/manifest.json`)"
      - "traefik.http.routers.assets.rule=PathPrefix(`/sockjs`)"
      - "traefik.http.routers.assets.entrypoints=web"
      - "traefik.http.routers.assets.priority=2"
