version: '2.4'
services:
    proxy:
        image: traefik:v2.2
        ports:
            - "80:80"
            - "8082:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: "--providers.docker --api.insecure=true --entrypoints.web.address=:80" 
        labels:
            - traefik.http.middlewares.auth.basicauth.users=$USERNAME:$PASSWORD_HASH
        restart: unless-stopped
    octoprint:
        build:
            context: .
            target: octoprint
        environment:
            PRIVATE_CAMERA_HOST: http://webcam:80
            POWER_IP: $PRINTER_POWER_IP
            API_KEY: $OCTOPRINT_API_KEY
        devices:
            - /dev/ttyACM0
        labels:
            - traefik.http.routers.octoprint.rule=PathPrefix(`/`)
            - traefik.http.routers.octoprint.middlewares=auth
        restart: unless-stopped
    webcam:
        build:
            context: .
            target: webcam
        environment:
            CAMERA_DEVICE: /dev/video0
        devices:
            - /dev/video0
        labels:
            - traefik.http.routers.webcam.rule=Query(`action=stream`)
            - traefik.http.routers.webcam.middlewares=auth
        restart: unless-stopped

