version: '2.4'
services:
    octoprint:
        build:
            context: .
            target: octoprint
        environment:
            PUBLIC_CAMERA_HOST: http://octopi.local:8081
            PRIVATE_CAMERA_HOST: http://webcam:80
            POWER_IP: $PRINTER_POWER_IP
        ports:
            - "8080:80" 
        devices:
            - /dev/ttyACM0
    webcam:
        build:
            context: .
            target: webcam
        environment:
            CAMERA_DEVICE: /dev/video0
        ports:
            - "8081:80" 
        devices:
            - /dev/video0
