accessControl:
    enabled: false
server:
    port: 80
    firstRun: false
    onlineCheck:
        enabled: false
    pluginBlacklist:
        enabled: false
    secretKey: $SECRET_KEY 
    seenWizards: # disable anon. tracking
        corewizard: 3
        tracking: null
webcam:
    ffmpeg: /usr/bin/ffmpeg
    ffmpegVideoCodec: libx264
    stream: $PUBLIC_CAMERA_HOST?action=stream
    snapshot: $PRIVATE_CAMERA_HOST?action=snapshot 
    streamRatio: '4:3'
    flipH: true # horizontally flip image
    watermark: false
    timelapse:
        fps: 25
        options:
            interval: 10
        postRoll: 2
        type: timed
folder:
    uploads: /uploads
    timelapse: /timelapse
plugins:
    tplinksmartplug:
        _config_version: 11
        arrSmartplugs:
        -   autoConnect: true
            autoConnectDelay: 5
            autoDisconnect: true
            autoDisconnectDelay: 0
            automaticShutdownEnabled: false
            btnColor: '#808080'
            countdownOffDelay: 1
            countdownOnDelay: 1
            currentState: unknown
            displayWarning: true
            emeter:
                get_realtime: {}
            icon: icon-bolt
            ip: $POWER_IP
            label: Power
            sysCmdOff: false
            sysCmdOffDelay: 0
            sysCmdOn: false
            sysCmdOnDelay: 0
            sysRunCmdOff: ''
            sysRunCmdOn: ''
            thermal_runaway: false
            useCountdownRules: false
            warnPrinting: true
