accessControl:
    enabled: false
server:
    port: 80
    firstRun: false
    onlineCheck:
        enabled: false
    pluginBlacklist:
        enabled: false
    secretKey: $SECRET_KEY 
    seenWizards: # disable anon. tracking
        corewizard: 3
        tracking: null
