accessControl:
  trustBasicAuthentication: true
  checkBasicAuthenticationPassword: false
server:
  firstRun: false
  onlineCheck:
    enabled: false
  pluginBlacklist:
    enabled: false
  seenWizards: # disable anon. tracking
    corewizard: 3
    tracking: null
folder:
  uploads: /uploads
  timelapse: /timelapse
