axes:
  e:
    inverted: false
    speed: 300
  x:
    inverted: false
    speed: 6000
  y:
    inverted: false
    speed: 6000
  z:
    inverted: false
    speed: 200
color: default
extruder:
  count: 1
  nozzleDiameter: 0.4
  offsets:
    - - 0.0
      - 0.0
  sharedNozzle: false
heatedBed: true
heatedChamber: false
id: _default
model: Prusa Mk2.5S
name: Prusa
volume:
  custom_box:
    x_max: 250.0
    x_min: 0.0
    y_max: 210.0
    y_min: -10.0
    z_max: 200.0
    z_min: 0.0
  depth: 210.0
  formFactor: rectangular
  height: 200.0
  origin: lowerleft
  width: 250.0
